public class Test {

	public Test() {
		// TODO 自動生成されたコンストラクター・スタブ
	}

	public static void main(String[] args) {

		String arg = "<AC_CM_RD_ENTER_CTR_ACC CORP_ID=\"-1000\" NATION_CODE=\"JPN\" BANK_CODE=\"0001\""
				+ " BRANCH_CODE=\"001\" BANKACCOUNT_ID=\"%s\" SEQ_NO=\"1\" CHANGE_DATE=\"1970-01-01 00:00:00.0\" DIARY_DIV=\"2\" "
				+ "DIARY_CHANGE_DIV=\"1\" DIARY_COUNT=\"0\" INPUT_APP_DIV=\"0\" BOOK_USER_DIV=\"0\" H_SECTION_DIV=\"0\" "
				+ "H_SECTION_ID=\"1\" ACCOUNT_TYPE=\"1\" ACCOUNT_NUM=\"00000%s\" ACCOUNT_NAME=\"ｺｳｻﾞ0000%s\""
				+ " CURRENCY_DIV=\"0\" FACT_CLIENT_NO=\"0\" START_DATE=\"1970-01-01 00:00:00.0\" "
				+ "END_DATE=\"2382-12-31 00:00:00.0\" SECTION_ID=\"-1\" SHARE_SECT_ID=\"99999\" "
				+ "SHARE_SECT_ID2=\"99999\" BSSEC_ID=\"1\" BSSEC_ID2=\"99999\" PAY_LIMIT=\"9999999999\" "
				+ "ORDER_VALUE=\"0\" FB_CONTRACT_FLG=\"1\" FACT_CONTRACT_FLG=\"0\" OVERDRAFT_FLG=\"0\" "
				+ "OVERDRAFT_AMOUNT=\"0\" RED_BALANCE=\"0\" DISUSE_ALERT_FLG=\"0\" DISUSE_ALERT_MONTH=\"24\" "
				+ "BALANCE_PRIORITY_DIV=\"1\" EBA_BANK_CODE=\"0001\" EBA_ACCNT=\"00110000%s\" "
				+ "EBA_REL_STATUS=\"1\" EBA_REL_KIND=\"1\" EBA_TRANS_PWD_TYPE=\"0\" "
				+ "EBA_APPROVAL_PWD_TYPE=\"0\" EBA_CONFIRMATION_PWD_TYPE=\"0\" EBA_BOOK_DIV=\"2\" "
				+ "EBA_MAINTE_TRANS_TYPE=\"0\" EBA_BAL_TRANS_TYPE=\"0\" EBA_BOOK_TRANS_TYPE=\"0\" EBA_PAY_TRANS_TYPE=\"0\" EBA_PRE_BALANCE_USE_DIV=\"0\" EBA_PAY_TRANS_ACCPT_USE_DIV=\"0\" EBA_PAY_TRANS_DATE_INPUT_DIV=\"0\" EBA_ACCPT_PAY_LIMIT=\"0\" EBA_ONETIME_PAY_LIMIT=\"0\" INT_MNG_DIV=\"1\" YC_INT_JNL_DIV=\"0\" YP_INT_JNL_DIV=\"0\" EXC_JNL_DIV=\"0\" D_CLOSING_DIV=\"1\" M_CLOSING_DIV=\"1\" D_CLOSING_CHECK_DIV=\"0\" D_CLOSING_SKIP_DIV=\"0\" M_CLOSING_DSKIP_DIV=\"0\" M_CLOSING_MSKIP_DIV=\"0\" M_CLOSING_START_YEARMONTH=\"5\" D_CLOSING_APP_DIV=\"1\" M_CLOSING_APP_DIV=\"1\" PAYMENT_ACCOUNT_DIV=\"0\" APP_ID=\"0\" APP_STATUS=\"0\" PROC_STATUS=\"21\" EXTRA_DIV1=\"0\" EXTRA_DIV2=\"0\" EXTRA_DIV3=\"0\" EXTRA_DIV4=\"0\" EXTRA_DIV5=\"0\" INPUT_DATETIME=\"1970-01-01 00:00:00.0\" INPUT_USER_ID=\"gtms\" LASTUPDATE_DATETIME=\"1970-01-01 00:00:00.0\" LASTUPDATE_USER_ID=\"gtms\" REC_STATUS=\"0\"/>";
		;
		for (int i = 1500; i <= 2000; i++) {
			String ttt = Integer.toString(i);
			String str = String.format(arg, ttt, ttt, ttt, ttt);
			System.out.println(str);
		}
	}
}
